version: '3.3'

services:

#  clamd:
#    image : neriberto/clamav
#    hostname : clamd
#    networks:
#      - vipernet
#    volumes:
#      - clamav-config:/etc/clamav/
#      - clamav-socket:/run/clamav/

  viper-web:
    build: viper/
    image: neriberto/viper_web
    hostname: viper-web
    networks:
      - vipernet
    ports:
      - "8080:8080"
    volumes:
        - viper-config:/root/.viper/
#    volumes_from:
#      - clamd
    command: viper-web -H 0.0.0.0

#  hg:
#    build: hg/
#    hostname: hg
#    networks:
#      - vipernet


volumes:
    clamav-config:
    clamav-socket:
    viper-config:

networks:
  vipernet:
    driver: bridge
