version: '2'

services:

  viperweb:
    image: neriberto/viper:prod
    hostname: viperweb
    networks:
      - vipernet
    ports:
      - "8080:8080"
    volumes:
        - viper-config:/root/.viper/
    command: viper-web -H 0.0.0.0

  nginx:
     image: neriberto/nginx:viper
     ports:
       - "80:80"
     networks:
       - vipernet
     depends_on:
       - viperweb

volumes:
    viper-config:

networks:
  vipernet:
    driver: bridge
