version: '2'

services:

  clamd:
    image : neriberto/clamav
    hostname : clamd
    container_name : clamd
    networks:
      - insecurenet
    volumes:
      - clamav-config:/etc/clamav/
      - clamav-socket:/run/clamav/

  viper-web:
    image: neriberto/viper
    hostname: viper-web
    container_name: viper-web
    networks:
      - insecurenet
    ports:
      - "9090:9090"
    volumes:
        - viper-config:/home/viper/.viper/
    volumes_from:
      - clamd
    command: ./viper-web -H 0.0.0.0 -p 9090

  viper-api:
    image: neriberto/viper
    hostname: viper-api
    container_name: viper-api
    networks:
      - insecurenet
    ports:
        - "8080:8080"
    volumes_from:
      - viper-web
    command: ./viper-api -H 0.0.0.0 -p 8080
  hg:
    build: hg/
    hostname: hg
    container_name: hg
    networks:
      - insecurenet


volumes:
    clamav-config:
    clamav-socket:
    viper-config:

networks:
  default:
  insecurenet:
    driver: bridge
