version: '2'

services:

  clamd:
    build : clamav/
    hostname : clamd
    container_name : clamd
    networks:
      - insecurenet
    volumes:
      - clamav-config:/etc/clamav/
      - clamav-socket:/run/clamav/

  viper:
    image: neriberto/viper
    hostname : viper
    container_name : viper
    networks:
      - insecurenet
    ports:
      - "9090:9090"
    volumes:
        - viper-config:/home/viper/.viper/
    volumes_from:
      - clamd
    command: ./viper-web -H 0.0.0.0 -p 9090

volumes:
    clamav-config:
    clamav-socket:
    viper-config:

networks:
  default:
  insecurenet:
    driver: bridge
